# -*- coding: utf-8 -*-
"""ExploratoryDataAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AeRscA826OnZHuVVqpdLGNGNHyZ3pgU6

# **TASK-3 : EXPLORATORY DATA ANALYSIS - RETAIL**

# **Name - Debadrita Debnath**

## **AIM : As a business manager, to work on the weaker areas on a business company to make effective profit through exploratory data analysis on the given dataset 'SampleSuperstore.csv'.**
## **PURPOSE : To derive the requisite problem solving techniques for bringing out continuity and consistency in the business normalisation.**
"""

# Importing the requisite libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from plotnine import *

# Importing the dataset
git_url='https://raw.githubusercontent.com/debadrita1517/The-Sparks-Foundation-Internship-Tasks/main/Task-3-Exploratory%20Data%20Analysis-Retail/SampleSuperstore.csv'
sample=pd.read_csv(git_url)
sample.head(5)

# Verifying the missing values
sample.isnull().sum()

# Getting the information of the data
sample.info()

# Getting the description of the variables
sample.describe()

# Deleting the variable 'Postal Code'
col=['Postal Code']
sample1=sample.drop(columns=col,axis=1)

# Showing the correlation between the variables
sample1.corr()

"""# **Data Visualization -**
**(Histogram Graphical Representation)**
"""

sample1.hist(bins=50,figsize=(20,15))
plt.show();

"""#**From the histograms, we can easily conclude that the data does NOT demonstrate a business continuity or consistency.**

# **Now, the following pie-chart shows the gain and loss of each and every sub-category -**
"""

# Showing the gain and loss of each and every subcategory in this business course
profit_plot=(ggplot(sample,aes(x='Sub-Category',y='Profit',fill='Sub-Category'))+geom_col()+coord_flip()+scale_fill_brewer(type='div',palette="Spectral")+theme_classic()+ggtitle('Pie Chart'))
display(profit_plot)

"""# **From the above pie-chart, we can jot down the following observations -**
```
1. the 'blinders' sub-category - suffered the HIGHEST amount of LOSS
```
```
2. the remaining sub-categories - GAINED(FOR NOW, the discount given on 'blinders' sub-category MIGHT be the reason)
```
```
3. the 'copiers' sub-category - gained HIGHEST amount of PROFIT(with low profit margins) with NO LOSS
```
```
4. the 'machines' sub-category - suffered the HIGHEST LOSS
```
"""

sns.set(style="whitegrid")
plt.figure(2,figsize=(20,15))
sns.barplot(x='Sub-Category',y='Profit',data=sample,palette='Spectral')
plt.suptitle('PIE CONSUMPTION PATTERNS IN THE UNITED STATES',fontsize=16)

# Plotting the Bar Graph showing the Ship Mode
ggplot(sample,aes(x='Ship Mode',fill='Category'))+geom_bar(stat='count')

"""# **Following pair plotting shows the relationship between each subcategories -**"""

# Pair Plotting the sub-category variables
figsize=(15,10)
sns.pairplot(sample1,hue='Sub-Category')

"""# **From the above plotting, it can be seen -**

*   **the data does NOT normalize the business continuity and consistency**
*   **the data comprises some amount of outliners**

# **Now, exploring further deep into the outliners using Boxplots -**

# **Step-1 : Checkingsales from every segment of the whole data of The United States.**
"""

flip_xlabels=theme(axis_text_x=element_text(angle=90, hjust=1),figure_size=(10,5),
                     axis_ticks_length_major=10,axis_ticks_length_minor=5)
(ggplot(sample, aes(x='Sub-Category', fill='Sales')) + geom_bar() + facet_wrap(['Segment']) 
+ flip_xlabels +theme(axis_text_x = element_text(size=12))+ggtitle("Sales From Every Segment Of United States of Whole Data"))

"""# **From the above graph, we can conclude the following -**

*   **The 'Home Office' segment - purchased the LOWEST SUB-CATEGORIES**
*   **The LOWEST Sales caused in the sub-categories -> 'Tables', 'Supplies', 'Machines', 'Copiers', 'Bookcases'**
*   **The 'Consumer' segment - purchased the HIGHEST SUB-CATEGORIES**

# **Now, the discount on categories from every segment of the whole data of The United States is on the following graphical display -**
"""

flip_xlabels=theme(axis_text_x = element_text(angle=90, hjust=1),figure_size=(10,5),
                     axis_ticks_length_major=10,axis_ticks_length_minor=5)
(ggplot(sample, aes(x='Sub-Category', fill='Discount')) + geom_bar() + facet_wrap(['Segment']) 
+ flip_xlabels +theme(axis_text_x = element_text(size=12))+ggtitle("DISCOUNT ON CATEGORIES FROM EVERY SEGMENT OF THE WHOLE DATA OF THE UNITED STATES"))

flip_xlabels = theme(axis_text_x = element_text(angle=90, hjust=10),figure_size=(10,10),axis_ticks_length_major=5,
                     axis_ticks_length_minor=5)
(ggplot(sample, aes(x='Category', y='Sales')) + geom_boxplot() + theme(axis_text_x = element_text(size=10)) 
+ facet_wrap(['State']) + flip_xlabels + coord_cartesian(ylim = (0, 2000))+ggtitle("Sales From Every State Of United States Of Whole Data"))

"""# **The above Box Plot Graph clearly visualizes the following -**
*   **in which common price range sales happened**
*   **the price range of categories in different cities**
*   **whether the sales are high/low in different states of The United States**

# **Now, the profit in each state is as follows -**
"""

flip_xlabels = theme(axis_text_x=element_text(angle=90, hjust=10),figure_size=(10,10),
                     axis_ticks_length_major=5,axis_ticks_length_minor=5)
(ggplot(sample, aes(x='Category', y='Profit')) + geom_boxplot() + theme(axis_text_x = element_text(size=10)) 
+ facet_wrap(['State']) + flip_xlabels+coord_cartesian(ylim = (-4000,5000))+ggtitle("PROFIT/LOSS IN EVERY STATE OF THE WHOLE DATA OF THE UNITED STATES"))

"""# **From the above graph, the following observations are to be taken -**

# **1.   HIGHEST LOSS - happened at 'Texas' state in the 'Office Supplies' category**
# **2.   NEAUTRAL change in either gain/loss - happenend in the states --> 'South Dakota', 'West Virginia', 'Wyoming', 'Maine', etc.**
# **3.   ONLY PROFIT was highlighted in the states --> 'Virginia', 'Washington', 'New York'**
"""

flip_xlabels=theme(axis_text_x = element_text(angle=90, hjust=10),figure_size=(10,10),
                     axis_ticks_length_major=50,axis_ticks_length_minor=50)
(ggplot(sample, aes(x='Category', fill='Sales')) + geom_bar() + theme(axis_text_x = element_text(size=10)) 
+ facet_wrap(['Region']) + flip_xlabels+ ggtitle("SALES FROM EVERY REGION OF THE WHOLE DATA OF THE UNITED STATES"))

"""# **From the above graph, we can observe the following -**
*   **Sales of 'Office Supplies' category - are HIGH in every region as compared to other categories**
*   **Sales in 'Technology' and 'Furniture'categories - are VERY LESS in South Region as compared to other regions of the US**
"""

flip_xlabels=theme(axis_text_x = element_text(angle=90, hjust=10),figure_size=(10,10),axis_ticks_length_major=5,axis_ticks_length_minor=5)
(ggplot(sample, aes(x='Region', fill='Quantity')) + geom_bar() + theme(axis_text_x = element_text(size=10)) 
+ facet_wrap(['Discount']) + flip_xlabels+ggtitle("DISCOUNT ON THE NUMBER OF QUANTITY FROM SALES OF THE UNITED STATES"))

"""# **From the above graph, we can conclude the 2 major points -**


*   **There were NO DISCOUNTS on higher number of quantities purchased in any region of the US.(May be, their selling price would be low.)**
*   **0.2% of Discount was given on higher number of quantities purchased in any region of the US.**
"""

flip_xlabels=theme(axis_text_x = element_text(angle=90, hjust=10),figure_size=(10,10),axis_ticks_length_major=5,axis_ticks_length_minor=5)
(ggplot(sample, aes(x='Category', y='Discount')) + geom_boxplot() + theme(axis_text_x = element_text(size=10)) 
+ facet_wrap(['State']) + flip_xlabels+ggtitle("DISCOUNT ON CATEGORIES ON EVERY STATE OF THE WHOLE DATA OF THE UNITED STATES"))

"""# **From the above graph, we can observe the following -**


*   **MOST DISCOUNT on categories is given on the states -> 'Texas', 'Oregon', 'Pennsylvania', 'Washington', 'Ohio', 'New York', 'Mexico', 'Utah', etc.**
*   **NO DISCOUNT on categories are given on the states -> 'Vermont', 'Virginia', 'Washington', West Virginia, etc.**

# **So now, we group/sum the sales, profit, discount and quantity with respect to every state of region and to sub-category sales as follows -**
"""

grouped=pd.DataFrame(sample.groupby(['Ship Mode','Segment','Category','Sub-Category','State','Region'])['Quantity','Discount','Sales','Profit'].sum().reset_index())
grouped

# sum, mean, min, max, count, median, standard deviation, variance of each states having Profit
sample.groupby("State").Profit.agg(["sum","mean","min","max","count","median","std","var"])

"""# **From the above statistical view, we can scoop out the following -**


*   **which states suffered the highest gain/loss in sales**
*   **the variant profit(whether it is high or low)**
*  **the median profit**
*   **the mean profit**
*   **the actual mean - will give an unbiased result as compared to median(since, mean considered whole data in calculation while median is not)**
"""

# Displaying sales from every region of the US after grouping
flip_xlabels = theme(axis_text_x = element_text(angle=90, hjust=10),figure_size=(10,10),axis_ticks_length_major=5,axis_ticks_length_minor=5)
(ggplot(grouped, aes(x='Category', fill='Sales')) + geom_bar() + theme(axis_text_x = element_text(size=10)) 
 + facet_wrap(['Region']) + flip_xlabels+ggtitle("SALES FROM EVERY REGION OF THE UNITED STATES AFTER GROUPING"))

# Displaying sales from every state of the US after grouping
flip_xlabels = theme(axis_text_x = element_text(angle=90, hjust=10),figure_size=(10,10),axis_ticks_length_major=5,axis_ticks_length_minor=5)
(ggplot(grouped, aes(x='Category', y='Sales')) + geom_boxplot() + theme(axis_text_x = element_text(size=10)) 
+ facet_wrap(['State']) + flip_xlabels+ggtitle("SALES FROM EVERY STATE OF THE UNITED STATES AFTER GROUPING"))

# Displaying profit/loss from every state of the US after grouping
flip_xlabels = theme(axis_text_x = element_text(angle=90, hjust=10),figure_size=(10,10),axis_ticks_length_major=5,axis_ticks_length_minor=5)
(ggplot(grouped, aes(x='Category', y='Profit')) + geom_boxplot() + theme(axis_text_x = element_text(size=10)) 
+ facet_wrap(['State']) + flip_xlabels+ggtitle("PROFIT/LOSS FROM EVERY STATE OF THE UNITED STATES AFTER GROUPING"))

# Displaying the discount given on categories from every state of the US after grouping
flip_xlabels = theme(axis_text_x = element_text(angle=90, hjust=10),figure_size=(10,10),axis_ticks_length_major=5,axis_ticks_length_minor=5)
(ggplot(grouped, aes(x='Category', y='Discount')) + geom_boxplot() + theme(axis_text_x = element_text(size=10)) 
+ facet_wrap(['State']) + flip_xlabels+ggtitle("DISCOUNT GIVEN ON CATEGORIES FROM EVERY STATE OF THE UNITED STATES AFTER GROUPING"))

"""# **From the above Box Plotting, we can observe the following -**
*   **HIGHEST DISCOUNT on different categories are in the states -> "Texas", "Pennsylvania", "New York City", "Ohio", "North Carolina", "California", "Florida", "Illionis"**
*   **On OTHER STATES - either there was NO DISCOUNT on categories or in very NEGLIGIBLE amount of discount was given**

# **On using K-Mean Clustering(Cluster Analysis) -**
"""

x=sample.iloc[:,[9,10,11,12]].values
from sklearn.cluster import KMeans
wcss=[]
for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++',max_iter=300,n_init=10,random_state=0).fit(x)
  wcss.append(kmeans.inertia_)

# Plotting the 'Sales' and 'Quantity' on the sub-categories
sns.set_style("whitegrid")
sns.FacetGrid(sample,hue="Sub-Category",height=6).map(plt.scatter,'Sales','Quantity')
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=100,c='yellow',label='Centroids')
plt.legend()

# Plotting the 'Sales' and 'Profit' on the sub-categories
sns.set_style("whitegrid")
sns.FacetGrid(sample,hue="Sub-Category",height=6).map(plt.scatter,'Sales','Profit')
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=100,c='yellow',label='Centroids')
plt.legend()

"""# **INTERPRETATION -**
## **From the above data visualization and clustering, we can easily interpret that in which states and in which categories sales and profits are high/less.**

# **CONCLUSION -**
## **We can bring business cosistency and continuity for normalisation in the respective states suffering loss by providing discounts in prefered range so that, the this Supertore Company as well as the consumers both will be in requisite gain.**
## **Such rectifications for the above business normalisation process can be done further through Factor Analysis or even through Neural Networking.**
"""